# Generated by Django 5.0.2 on 2024-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_Title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=400)),
                ('duration', models.DurationField(max_length=400)),
                ('achievments', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Myprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_decription', models.CharField(max_length=10000)),
                ('tech_used', models.CharField(max_length=1000)),
                ('link_url', models.URLField()),
            ],
        ),
    ]
