# Generated by Django 4.2.5 on 2024-02-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myresume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprojects',
            old_name='project_decription',
            new_name='project_description',
        ),
    ]
